theme: jekyll-theme-cayman
title: gennnius
brief-intro:菜鸟的成长之路

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gennnius.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
#twitter_username: 
#facebook_username: 
github_username:  gennnius
email: zhanhaooo@163.com
#weibo_username: 
#zhihu_username: 
#linkedIn_username: 
#dribbble_username:
